import { StyleSheet, Dimensions } from 'react-native';
const screen = Dimensions.get("window");

export default styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    paddingTop: screen.height/22,
  },
  groupTitle: {
    paddingTop: 20,
    fontSize: 30,
    color: '#ffffff',
    fontWeight: 'bold',
  },
  searchContainer: {
    backgroundColor: 'transparent',
    width: screen.width - 30,
    borderRadius: 45,
    height: screen.height / 4,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  memberText: {
    fontWeight: 'bold',
    color: '#000000',
    paddingTop: 30,
    paddingLeft: screen.width / 10,
    fontSize: 20,
  },
  buttonContainer: {
    paddingLeft: screen.width / 10,
    paddingRight: screen.width/10,
    height: screen.height/5,
    width: screen.width/1.3,
    backgroundColor: '#ffffff',
    borderRadius: 25,
    justifyContent: "center",
    alignItems: "center", 
  },
  row: {
    flex: 1,
    justifyContent: "space-around",
  },
  button:{
    flex: 1,
    height: 60,
    paddingTop: 10,
    paddingLeft: screen.width/20,
  },
  buttonText: {
    fontWeight: 'bold',
    fontSize: 16,
    paddingTop: 10,
    textAlign: "center",
  },
  search: {
    borderRadius: 30,
    borderColor: '#000',
    backgroundColor: '#ffffff',
    borderLeftWidth: 0.5,
    borderRightWidth: 0.5,
    borderBottomWidth: 0.5,
    borderTopWidth: 0.5,
    elevation: 5,
    maxHeight: 40,
  },
  searchText: {
    paddingLeft: 10,
  },
  friendButton: {
    backgroundColor: '#ffffff',
    height: screen.height/6.5,
    width: screen.height/6.5,
    margin: 15,
    padding: 10,
    borderRadius: 25,
    alignItems: "center",
    justifyContent: "center",
    textAlign: 'center',
    elevation: 20,
  },
  modalBackground: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    height: screen.height,
    width: screen.width,
    backgroundColor: '#000000aa',
  },
  backImage:{
    width: 30,
    height: 30,
  },
  backButton:{
    paddingBottom: 10,
    paddingRight: 230,
  },
  modalButton: {
    backgroundColor: "#ebebeb",
    width: screen.width/3,
    height: screen.width/5,
    margin: 10,
    borderRadius: 25,
    alignItems: "center",
    textAlign: "center",
    justifyContent: "center",
  },
  listGroups: {
    height: screen.height/2.6,
    backgroundColor: 'white',
    borderRadius: 25,
    width: screen.width,
    padding: 30,
  },
  listGroupsHeader: {
    paddingBottom: 20,
    color: 'black',
    fontWeight: 'bold',
    fontSize: 20,
    paddingRight: 200,
  },
  listComponent:{
    margin: 5,
    height: 30,
    width: 200,
    borderRadius: 10,
    alignItems: 'center',
  }
});